name: tenzi_za_rohoni
description: Kitabu cha tenzi za Rohoni

# Vidokezo vya Toleo (Release Notes)
#
# - Mandhari mpya ya kisasa na rangi laini
# - Maboresho ya ukurasa wa maelezo na ukurasa wa nyimbo pendwa
# - Uwezo wa kutathmini/kupima app moja kwa moja
# - Utafutaji wa nyimbo kwa urahisi
# - Orodha ya nyimbo pendwa na kuhifadhi chaguo zako
# - Kushiriki nyimbo kwa urahisi
# - Maboresho ya utendaji na marekebisho ya hitilafu ndogo

publish_to: "none"

version: 2.0.1+6

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.0
  flutter_share: ^2.0.0
  url_launcher: ^6.1.12
  in_app_review: ^2.0.6
  # wakelock: ^0.6.2
  rate_my_app: ^2.0.0

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.13.1"

flutter:
  uses-material-design: true

  assets:
    - assets/tenzi.json
    - assets/images/
    - assets/icons/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/tenzi_icon.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/icons/tenzi_icon.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/icons/tenzi_icon.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/icons/tenzi_icon.png"
